knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        # the key "facebook_main" can be anything, it
        # will create a service: "knpu.oauth2.client.facebook_main"
        google:
            # this will be one of the supported types
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_google_check
            redirect_params: {}
        facebook:
          type: facebook
          client_id: '%env(FB_ID)%'
          client_secret: '%env(FB_SECRET)%'
          redirect_route: connect_facebook_check
          redirect_params: {}
          graph_api_version: v2.12